---
# Some of this info was necessary for this to work:
# https://discuss.elastic.co/t/logstash-s3-output-plugin-with-aws-emulation-with-localstack/255822
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack.d:/docker-entrypoint-initaws.d
  
 
  logstash:
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
    build: logstash
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_BUCKET: logstash-bucket
      AWS_ENDPOINT: http://localstack:4566
      LOGSTASH_USER: logstash
      LOGSTASH_PASSWORD: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
      - "9700:9700"

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    depends_on:
      logstash:
        condition: service_healthy
    volumes:
      - .:/app
