---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          chmod -R 777 logstash
          PWD=`pwd` make logstash-installation
          # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o logstash/awscliv2.zip
          # curl https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.16.3-linux-x86_64.tar.gz -o logstash/logstash-oss-7.16.3-linux-x86_64.tar.gz
          # docker run -v `pwd`:`pwd` -w `pwd` --rm docker.elastic.co/logstash/logstash-oss:7.16.3 bin/prepare-offline-logstash
          docker compose run --rm test
