---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          docker compose  run --rm  logstash pwd
          docker compose  run --rm  logstash ls -R
