---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          docker compose up -d &
          sleep 160
          docker inspect --format='{{json .State.Health}}' datagov-logstack_logstash_1
          netstat -tuplen
