---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          docker compose up -d &
          sleep 400
          docker ps -A
          docker inspect --format='{{json .State.Health}}' datagov-logstack-logstash-1
          netstat -tuplen
