---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          docker compose up logstash &
          sleep 120
          docker exec datagov-logstack-logstash-1 pwd
          docker exec datagov-logstack-logstash-1 ls -R
