---
name: dev-deploy

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  # create-cloudgov-services-development-ssb:
  #   name: create services (development-ssb)
  #   environment: development-ssb
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: create services
  #       uses: cloud-gov/cg-cli-tools@main
  #       with:
  #         command: ./create-cloudgov-services.sh
  #         cf_org: gsa-datagov
  #         cf_space: development-ssb
  #         cf_username: ${{secrets.CF_SERVICE_USER}}
  #         cf_password: ${{secrets.CF_SERVICE_AUTH}}

  deploy-development-ssb:
    name: deploy (development-ssb)
    environment: development-ssb
    runs-on: ubuntu-latest
    # needs:
    #   - create-cloudgov-services-development-ssb
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: build dependencies
      #   run: |
      #     chmod -R 777 logstash
      #     PWD=`pwd` make logstash-installation
      - name: deploy-logstash
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf push --vars-file vars.development-ssb.yml --strategy rolling
          cf_org: gsa-datagov
          cf_space: development-ssb
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      # - name: smoke test logstash
      #   run: |
      #     sleep 150  # Logstash is very slow to start up
      #     [ "401" = "$(curl -w '%{http_code}' --output /dev/null --silent https://logstash-development-datagov.app.cloud.gov)" ]

  drain-apps-in-development-ssb:
    name: drain apps in development-ssb space
    environment: development-ssb
    runs-on: ubuntu-latest
    needs:
      - deploy-development-ssb
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: drain-development-ssb-space
        uses: cloud-gov/cg-cli-tools@37d58fc10abf00a45926e8886879c81a498f7ea8
        with:
          command: |
            ./create-space-drain.sh development-ssb
          cf_org: gsa-datagov
          cf_space: development-ssb
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}   
       
  # drain-apps-in-development:
  #   name: drain apps in development space
  #   environment: development
  #   runs-on: ubuntu-20.04
  #   # needs:
  #   #   - deploy-development-ssb
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: drain-development-space
  #       uses: cloud-gov/cg-cli-tools@main
  #       with:
  #         command: |
  #           ./create-space-drain.sh development-ssb
  #         cf_org: gsa-datagov
  #         cf_space: development
  #         cf_username: ${{secrets.CF_SERVICE_USER}}
  #         cf_password: ${{secrets.CF_SERVICE_AUTH}}
