---
name: publish & deploy

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    name: publish LogStash docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish logstack image
        uses: docker/build-push-action@v2
        env:
          TAG: ${{ github.ref_name }}
        with:
          context: logstash
          push: true
          tags: ghcr.io/gsa/datagov-logstash:${{ env.TAG }}
          labels: latest
  
  create-cloudgov-services-management-staging:
    name: create services (management-staging)
    environment: management-staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create services
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: ./create-cloudgov-services.sh
          cf_org: gsa-datagov
          cf_space: management-staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}} 
  
  deploy-management-staging:
    name: deploy (management-staging)
    environment: management-staging
    runs-on: ubuntu-latest
    needs:
      - publish
      - create-cloudgov-services-management-staging
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy-logstash
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: cf push --vars-file vars.management-staging.yml --strategy rolling
          cf_org: gsa-datagov
          cf_space: management-staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test logstash
        run: |
          sleep 40  # Logstash is very slow to start up 
          [ "401" = "$(curl -w '%{http_code}' --output /dev/null --silent https://logstash-stage-datagov.app.cloud.gov)" ]

  create-cloudgov-services-management:
    name: create services (management)
    environment: management
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create services
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: ./create-cloudgov-services.sh
          cf_org: gsa-datagov
          cf_space: management
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}

  deploy-management:
    name: deploy (management)
    environment: management
    runs-on: ubuntu-latest
    needs:
      - create-cloudgov-services-management
      - deploy-management-staging
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy-logstash
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: cf push --vars-file vars.management.yml --strategy rolling
          cf_org: gsa-datagov
          cf_space: management
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: smoke test
        run: |
          sleep 20  # Logstash is very slow to start up
          [ "401" = "$(curl -w '%{http_code}' --output /dev/null --silent https://logstash-stage-datagov.app.cloud.gov)" ]

  drain-apps-in-staging:
    name: drain everything in staging space
    environment: staging
    runs-on: ubuntu-latest
    needs:
      - deploy-management
    steps:
      - name: drain-staging-space
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: cf install-plugin -f -r CF-Community "drains" && ./create-space-drain.sh
          cf_org: gsa-datagov
          cf_space: staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}

  drain-apps-in-prod:
    name: drain everything in prod space
    environment: production
    runs-on: ubuntu-latest
    needs:
      - deploy-management
    steps:
      - name: drain-prod-space
        uses: cloud-gov/cg-cli-tools@cli-v8
        with:
          command: cf install-plugin -f -r CF-Community "drains" && ./create-space-drain.sh
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
